//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using SimpleJSON;

namespace OpenWorld
{

    public sealed partial class Tables
    {
        public item.TDEquipTable TDEquipTable { get; }

        public Tables(System.Func<string, JSONNode> loader)
        {
            var tables = new System.Collections.Generic.Dictionary<string, object>();
            TDEquipTable = new item.TDEquipTable(loader("item_tdequiptable"));
            tables.Add("item.TDEquipTable", TDEquipTable);
            PostInit();

            TDEquipTable.Resolve(tables);
            PostResolve();
        }

        public void TranslateText(System.Func<string, string, string> translator)
        {
            TDEquipTable.TranslateText(translator);
        }

        partial void PostInit();
        partial void PostResolve();
    }

}
