#ifndef RENDERPIPELINE_UNITYINPUT_INCLUDED
#define RENDERPIPELINE_UNITYINPUT_INCLUDED


CBUFFER_START(UnityPerMaterial)
half4 _BaseColor;
real _Cutoff;
CBUFFER_END


TEXTURE2D(_BaseTex);SAMPLER(sampler_BaseTex);

#endif